[package]
name = "brisk_auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.5.0"
hmac-sha1 = "0.2.2"
security-framework = "2.9.2"
core-foundation = "0.9.3"
